# **Libraries and Dataset**

In [ ]:
# Data cleaning
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
sales_path = '/content/drive/My Drive/MDTM15/Raw Datasets/Sales_forecast/sales_data_set.csv'
stores_path = '/content/drive/My Drive/MDTM15/Raw Datasets/Sales_forecast/stores_data_set.csv'
features_path = '/content/drive/My Drive/MDTM15/Raw Datasets/Sales_forecast/Features_data_set.csv'
sales_df = pd.read_csv(sales_path)
stores_df = pd.read_csv(stores_path)
features_df = pd.read_csv(features_path)

# **Stores_DataFrame**

In [ ]:
stores_df.head()

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [ ]:
stores_df.isnull().sum()

Store    0
Type     0
Size     0
dtype: int64

In [ ]:
stores_df.shape

(45, 3)

# **Sales_DataFrame**

In [ ]:
sales_df.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  05/02/2010      24924.50      False
1      1     1  12/02/2010      46039.49       True
2      1     1  19/02/2010      41595.55      False
3      1     1  26/02/2010      19403.54      False
4      1     1  05/03/2010      21827.90      False

In [ ]:
sales_df.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [ ]:
sales_df.shape

(421570, 5)

# **Features_DataFrame**

In [ ]:
features_df.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,12/02/2010,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,19/02/2010,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,26/02/2010,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,05/03/2010,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [ ]:
features_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   object
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     4032 non-null   float64
 5   MarkDown2     2921 non-null   float64
 6   MarkDown3     3613 non-null   float64
 7   MarkDown4     3464 non-null   float64
 8   MarkDown5     4050 non-null   float64
 9   CPI           7605 non-null   float64
 10  Unemployment  7605 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(1), object(1)
memory usage: 712.0+ KB

In [ ]:
features_df.shape

(8190, 12)

In [ ]:
features_df.MarkDown1.fillna(0, inplace = True)
features_df.MarkDown2.fillna(0, inplace = True)
features_df.MarkDown3.fillna(0, inplace = True)
features_df.MarkDown4.fillna(0, inplace = True)
features_df.MarkDown5.fillna(0, inplace = True)

In [ ]:
features_df['CPI'].fillna(method='ffill', inplace=True)
features_df['Unemployment'].fillna(method = 'ffill', inplace = True)

In [ ]:
features_df.isnull().sum()

Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

# **1.Identify average customer visit in the type B store in April Months**

In [ ]:
sales_df['Date'] = pd.to_datetime(sales_df['Date'], format='%d/%m/%Y')
features_df['Date'] = pd.to_datetime(features_df['Date'], format='%d/%m/%Y')

In [ ]:
import pandas as pd

# Assuming sales_df, features_df, and stores_df are already defined
# Filter Type B stores
stores_df_type_b = stores_df[stores_df['Type'] == 'B']
stores_df_type_b

    Store Type    Size
2       3    B   37392
4       5    B   34875
6       7    B   70713
8       9    B  125833
9      10    B  126512
11     12    B  112238
14     15    B  123737
15     16    B   57197
16     17    B   93188
17     18    B  120653
20     21    B  140167
21     22    B  119557
22     23    B  114533
24     25    B  128107
28     29    B   93638
34     35    B  103681
44     45    B  118221

In [ ]:
# Filter sales dataframe for Type B stores and for April months
april_sales_df = sales_df[(sales_df['Date'].dt.month == 4) & (sales_df['Store'].isin(stores_df_type_b['Store']))]

sales_years = april_sales_df['Date'].dt.year.unique()

april_sales_df

        Store  Dept       Date  Weekly_Sales  IsHoliday
20490       3     1 2010-04-02      16399.01      False
20491       3     1 2010-04-09       8316.05      False
20492       3     1 2010-04-16       4061.89      False
20493       3     1 2010-04-23       4417.17      False
20494       3     1 2010-04-30       4159.25      False
...       ...   ...        ...           ...        ...
421491     45    98 2011-04-29        868.74      False
421540     45    98 2012-04-06        778.70      False
421541     45    98 2012-04-13        559.14      False
421542     45    98 2012-04-20        605.80      False
421543     45    98 2012-04-27        619.41      False

[16007 rows x 5 columns]

In [ ]:
sales_years

array([2010, 2011, 2012], dtype=int32)

In [ ]:
# Filter features dataframe for April of the same year

april_features_df = features_df[
    (features_df['Date'].dt.month == 4) &
    (features_df['Date'].dt.year.isin(sales_years)) &
    (features_df['Store'].isin(stores_df_type_b['Store']))]

# Sum up the weekly sales for Type B stores in April
april_sales_total = april_sales_df['Weekly_Sales'].sum()

# Calculate the sum of the CPI for Type B stores in April
april_cpi_total = april_features_df['CPI'].sum()

# Calculate the average customer visit
average_customer_visit = april_sales_total / april_cpi_total

print("Average customer visit in Type B stores in April:", average_customer_visit)

Average customer visit in Type B stores in April: 4784.998759564955

In [ ]:
import pandas as pd

In [ ]:
merged_df = pd.merge(features_df, sales_df, on=['Store', 'Date'])
df = pd.merge(merged_df, stores_df, on=['Store'])

In [ ]:
df

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_x,Dept,Weekly_Sales,IsHoliday_y,Type,Size
0,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,1,24924.50,False,A,151315
1,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,2,50605.27,False,A,151315
2,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,3,13740.12,False,A,151315
3,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,4,39954.04,False,A,151315
4,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,5,32229.38,False,A,151315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,93,2487.80,False,B,118221
421566,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,94,5203.31,False,B,118221
421567,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,95,56017.47,False,B,118221
421568,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,97,6817.48,False,B,118221
421569,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,98,1076.80,False,B,118221

In [ ]:
df.isnull().sum()

Store                0
Date                 0
Temperature          0
Fuel_Price           0
MarkDown1       270889
MarkDown2       310322
MarkDown3       284479
MarkDown4       286603
MarkDown5       270138
CPI                  0
Unemployment         0
IsHoliday_x          0
Dept                 0
Weekly_Sales         0
IsHoliday_y          0
Type                 0
Size                 0
dtype: int64